### ISSUE TITLE
Failing to install deps in the Example app.

### ISSUE THREAD

**Issue by rasjonell-zz** [amolenaar/elixir_lambda#3]
Hello, I've tried using this runtime with your provided example and everything worked fine.
But when I tried to add some dependencies to the example app the `make` command threw this error when trying to run the example app:
```sh
docker run -w /code -v /Users/rasjonell/Desktop/experimental/elixir_lambda/example:/code -u 501:20 -e MIX_ENV=prod elixir-runtime mix do setup, package
Could not find Hex, which is needed to build dependency :velocy
Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn] ** (Mix) Could not find an SCM for dependency :velocy from Example.MixProject
make: *** [example/example-0.1.0.zip] Error 1
```

So I added an alias to `mix.exs` like so:
```ex
[
  "setup": ["local.hex --force", "deps.get"]
]
```

Then when I ran the `make` command again it threw another error:
```sh
** (File.Error) could not make directory (with -p) "/.mix/archives/hex-0.20.1": no such file or directory
    (elixir) lib/file.ex:314: File.mkdir_p!/1
    (mix) lib/mix/tasks/archive.install.ex:113: Mix.Tasks.Archive.Install.install/3
    (mix) lib/mix/local/installer.ex:107: Mix.Local.Installer.local_install/3
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:365: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:292: Mix.Task.run/2
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
```

**Comment by rasjonell-zz** [comment]
so apparently the problem was `-u 501:20` argument passed to `docker run`. The user did not have access to write the directory. Removing it solved the problem. Closing the issue.
